### ISSUE TITLE
add C++ generator option

### ISSUE THREAD

**Issue by GavinZhengOI** [art-hack/Codeforces-HackAssistant#1]
I think use C++ generator is a better idea. Because C++ is much faster than Python. 

My checker is using C++ generator and it can check 10,000 case in minutes.

![](https://gvz-blog.oss-cn-chengdu.aliyuncs.com/img/20200324001405.png)

**Comment by art-hack** [comment]
Yes, that could help, perhaps I will add an option to use either Python or C++ for the generator. It would be great if you will share link to your checker.

**Comment by GavinZhengOI** [comment]
> Yes, that could help, perhaps I will add an option to use either Python or C++ for the generator. It would be great if you will share link to your checker.

https://pastebin.ubuntu.com/p/hgzVzyNkkn/
